stages:
  - test
  - package

image: python:latest

job_build:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - cd app/
  script:
    - python -m tests.test_app

job_package:
  stage: package
  script:
    - echo "realizar o build da imagem"
    - echo "realizar o login no registry"
    - echo "realizar o envio da imagem "

